# docker-compose.yml

# Specify the version of Docker Compose to use
version: '3.8'

# Define a custom network named 'Netception'
networks:
  Netception:

# Define the services that make up your app
services:
  # The nginx service
  nginx:
    # The name of the container when it is started
    container_name: nginx
    # The location of the Dockerfile for this service
    build: ./requirements/nginx
    # The name of the image to build
    image: img_nginx
    # Mount host paths or named volumes, specified as sub-options to a service
    volumes:
      - "~/Desktop/Inception/website:/var/www/html"
    # Connect this service to the 'Netception' network
    networks:
      - Netception
    # Expose ports. Format: host:container
    ports:
      - "443:443" 
    # Express dependency between services
    depends_on:
      - wordpress
    # Restart policy to apply when a container exits
    restart: always

  # The wordpress service
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    volumes:
      - "~/Desktop/Inception/website:/var/www/html"
    networks:
      - Netception
    # Add environment variables
    environment: 
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}
    restart: always

  # The mariadb service
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - Netception
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
    restart: always